[package]
name = "simple-mic-lock"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.2"
egui = "0.36.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = { version = "0.24.2", default-features = false, features = ["common-controls-v6"] }
windows-core = "0.62"

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_FunctionDiscovery",
    "Win32_Globalization",
    "Win32_Graphics_Gdi",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[build-dependencies]
embed-resource = "3.0.11"
resvg = { version = "0.48.1", default-features = false }
